#!/usr/bin/env bash

set -e

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export CONTRACTS_BASE_DIR="${this_dir}/contracts"

./mb restart --configfile contracts/imposters.ejs --allowInjection
